### ISSUE TITLE
Both the values are correct. Still showing this error

### ISSUE THREAD

**Issue by NflixMovies** [Jack-of-tg/MEDIA-EDITOR-BOT#9]
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    app.run()
  File "/usr/local/lib/python3.8/site-packages/pyrogram/methods/utilities/run.py", line 61, in run
    self.start()
  File "/usr/local/lib/python3.8/site-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/pyrogram/methods/utilities/start.py", line 57, in start
    await self.authorize()
  File "/usr/local/lib/python3.8/site-packages/pyrogram/client.py", line 281, in authorize
    return await self.sign_in_bot(self.bot_token)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/methods/auth/sign_in_bot.py", line 46, in sign_in_bot
    r = await self.send(
  File "/usr/local/lib/python3.8/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/usr/local/lib/python3.8/site-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ApiIdInvalid: [400 API_ID_INVALID]: The api_id/api_hash combination is invalid (caused by "auth.ImportBotAuthorization")

**Comment by Jack-of-tg** [comment]
> Traceback (most recent call last): File "main.py", line 41, in app.run() File "/usr/local/lib/python3.8/site-packages/pyrogram/methods/utilities/run.py", line 61, in run self.start() File "/usr/local/lib/python3.8/site-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap return loop.run_until_complete(coroutine) File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete return future.result() File "/usr/local/lib/python3.8/site-packages/pyrogram/methods/utilities/start.py", line 57, in start await self.authorize() File "/usr/local/lib/python3.8/site-packages/pyrogram/client.py", line 281, in authorize return await self.sign_in_bot(self.bot_token) File "/usr/local/lib/python3.8/site-packages/pyrogram/methods/auth/sign_in_bot.py", line 46, in sign_in_bot r = await self.send( File "/usr/local/lib/python3.8/site-packages/pyrogram/methods/advanced/send.py", line 77, in send r = await self.session.send( File "/usr/local/lib/python3.8/site-packages/pyrogram/session/session.py", line 425, in send return await self._send(data, timeout=timeout) File "/usr/local/lib/python3.8/site-packages/pyrogram/session/session.py", line 395, in _send RPCError.raise_it(result, type(data)) File "/usr/local/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it raise getattr( pyrogram.errors.exceptions.bad_request_400.ApiIdInvalid: [400 API_ID_INVALID]: The api_id/api_hash combination is invalid (caused by "auth.ImportBotAuthorization")

Check it one more time 😅
